// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YouScanDashboard.Server.Data;

#nullable disable

namespace YouScanDashboard.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YouScanDashboard.Server.Domain.Dataset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("SourceKey")
                        .HasColumnType("text")
                        .HasColumnName("source_key");

                    b.HasKey("Id")
                        .HasName("pk_datasets");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_datasets_source_key");

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("YouScanDashboard.Server.Domain.Widget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid?>("DatasetId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_widgets");

                    b.HasIndex("DatasetId")
                        .HasDatabaseName("ix_widgets_dataset_id");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_widgets_position");

                    b.ToTable("widgets", (string)null);
                });

            modelBuilder.Entity("YouScanDashboard.Server.Domain.Widget", b =>
                {
                    b.HasOne("YouScanDashboard.Server.Domain.Dataset", "Dataset")
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_widgets_datasets_dataset_id");

                    b.Navigation("Dataset");
                });
#pragma warning restore 612, 618
        }
    }
}
